name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-option: [ '--verbose',' --release --verbose' ]

    steps:
    - uses: actions/checkout@v4

    - name: Document
      run: cargo doc

    - name: Build
      run: |
        cargo build ${{ matrix.build-option }}

    - name: Run tests
      run: cargo test --verbose

    - name: Coverage
      run: |
        cargo install grcov
        rustup component add llvm-tools
        CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='./target/coverage/test.profraw' cargo test
        grcov . --binary-path ./target/debug/deps/ --source-dir . --output-types html --output-path ./target/coverage/
